steps :

# build docker image 
- name: 'gcr.io/cloud-builders/docker'
  id: Build Image cards-new-platform Service 
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/cards-new-platform:latest'
  - '-f'
  - 'Dockerfile'
  - '.'

# docker push to container registry
- name: 'gcr.io/cloud-builders/docker'
  id: Publish Image cards-new-platform  Service 
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/cards-new-platform:latest'

# Clone deploy repository
- name: 'gcr.io/cloud-builders/gcloud'
  id: Clone deployment repository
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    git clone https://github.com/sundaresanhariprasad/cardless-service-deployments.git && \
    cd cardless-service-deployments && \
    git checkout main && \
    git config user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)')


- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy cards legacy service to GKE Cluster
  args:
  - 'apply'
  - '-f'
  - './cardless-service-deployments/k8/cards-new-platform'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cardless-gke-cluster'
